"""change morphology items to composite primary key

Revision ID: 620104f5f002
Revises: e7a8b694d2dd
Create Date: 2026-03-05 11:05:17.126380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '620104f5f002'
down_revision: Union[str, None] = 'e7a8b694d2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verses_id', table_name='verses')
    op.drop_index('ix_verses_surah_number', table_name='verses')
    op.drop_index('ix_verses_verse_number', table_name='verses')
    op.drop_table('verses')
    op.drop_index('ix_surahs_id', table_name='surahs')
    op.drop_index('ix_surahs_number', table_name='surahs')
    op.drop_table('surahs')
    op.drop_index('ix_morphology_items_chapter', table_name='morphology_items')
    op.drop_index('ix_morphology_items_id', table_name='morphology_items')
    op.drop_index('ix_morphology_items_token', table_name='morphology_items')
    op.drop_index('ix_morphology_items_verse', table_name='morphology_items')
    op.drop_index('ix_morphology_items_word_num', table_name='morphology_items')
    op.drop_column('morphology_items', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('morphology_items', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_morphology_items_word_num', 'morphology_items', ['word_num'], unique=False)
    op.create_index('ix_morphology_items_verse', 'morphology_items', ['verse'], unique=False)
    op.create_index('ix_morphology_items_token', 'morphology_items', ['token'], unique=False)
    op.create_index('ix_morphology_items_id', 'morphology_items', ['id'], unique=False)
    op.create_index('ix_morphology_items_chapter', 'morphology_items', ['chapter'], unique=False)
    op.create_table('surahs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name_arabic', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name_english', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('revelation_place', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('verses_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='surahs_pkey')
    )
    op.create_index('ix_surahs_number', 'surahs', ['number'], unique=True)
    op.create_index('ix_surahs_id', 'surahs', ['id'], unique=False)
    op.create_table('verses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('surah_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('verse_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text_arabic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('text_simple', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('translation_english', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='verses_pkey')
    )
    op.create_index('ix_verses_verse_number', 'verses', ['verse_number'], unique=False)
    op.create_index('ix_verses_surah_number', 'verses', ['surah_number'], unique=False)
    op.create_index('ix_verses_id', 'verses', ['id'], unique=False)
    # ### end Alembic commands ###
