"""add isms table

Revision ID: 63ad7b70fac0
Revises: 8fa00af61d24
Create Date: 2026-03-05 12:30:57.949685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ad7b70fac0'
down_revision: Union[str, None] = '8fa00af61d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isms',
    sa.Column('ism', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('heaviness', sa.Enum('LIGHT', 'HEAVY', name='heavinessenum'), nullable=False),
    sa.Column('ism_type', sa.Enum('PROPER', 'COMMON', name='ismtypeenum'), nullable=True),
    sa.Column('flexibility', sa.Enum('FLEXIBLE', 'PARTIAL', 'NON_FLEXIBLE', name='flexibilityenum'), nullable=True),
    sa.Column('root', sa.String(length=255), nullable=True),
    sa.Column('lem', sa.String(length=255), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verse', sa.Integer(), nullable=False),
    sa.Column('word_num', sa.Integer(), nullable=False),
    sa.Column('token', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ism')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('isms')
    # ### end Alembic commands ###
