"""Added enums for gender and number

Revision ID: 774747aea383
Revises: 91bbe687921e
Create Date: 2026-03-06 03:59:31.887615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '774747aea383'
down_revision: Union[str, None] = '91bbe687921e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum types first
    numberenum = sa.Enum('SINGULAR', 'DUAL', 'PLURAL', name='numberenum')
    numberenum.create(op.get_bind(), checkfirst=True)

    genderenum = sa.Enum('MASCULINE', 'FEMININE', name='genderenum')
    genderenum.create(op.get_bind(), checkfirst=True)

    # Also update enum values for existing enums
    heavinessenum = sa.Enum('LIGHT', 'HEAVY', name='heavinessenum')
    heavinessenum.create(op.get_bind(), checkfirst=True)

    ismtypeenum = sa.Enum('PROPER', 'COMMON', name='ismtypeenum')
    ismtypeenum.create(op.get_bind(), checkfirst=True)

    flexibilityenum = sa.Enum('FLEXIBLE', 'PARTIAL', 'NON_FLEXIBLE', name='flexibilityenum')
    flexibilityenum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    # Convert VARCHAR columns to enum types using CAST
    op.execute('ALTER TABLE isms ALTER COLUMN number TYPE numberenum USING number::numberenum')
    op.execute('ALTER TABLE isms ALTER COLUMN gender TYPE genderenum USING gender::genderenum')

    # Update existing enum values to uppercase
    op.execute('ALTER TABLE isms ALTER COLUMN heaviness TYPE heavinessenum USING heaviness::text::heavinessenum')
    op.execute('ALTER TABLE isms ALTER COLUMN ism_type TYPE ismtypeenum USING ism_type::text::ismtypeenum')
    op.execute('ALTER TABLE isms ALTER COLUMN flexibility TYPE flexibilityenum USING flexibility::text::flexibilityenum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('isms', 'gender',
               existing_type=sa.Enum('MASCULINE', 'FEMININE', name='genderenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('isms', 'number',
               existing_type=sa.Enum('SINGULAR', 'DUAL', 'PLURAL', name='numberenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###

    # Drop the enum types
    sa.Enum(name='numberenum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='genderenum').drop(op.get_bind(), checkfirst=True)
