"""Set heaviness to be optional

Revision ID: 91bbe687921e
Revises: 63ad7b70fac0
Create Date: 2026-03-05 12:51:35.014288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91bbe687921e'
down_revision: Union[str, None] = '63ad7b70fac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('isms', 'heaviness',
               existing_type=postgresql.ENUM('LIGHT', 'HEAVY', name='heavinessenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('isms', 'heaviness',
               existing_type=postgresql.ENUM('LIGHT', 'HEAVY', name='heavinessenum'),
               nullable=False)
    # ### end Alembic commands ###
