"""initial migration

Revision ID: 932e13df7124
Revises: 
Create Date: 2026-03-04 13:09:52.084722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932e13df7124'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surahs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name_arabic', sa.String(length=255), nullable=False),
    sa.Column('name_english', sa.String(length=255), nullable=False),
    sa.Column('revelation_place', sa.String(length=50), nullable=True),
    sa.Column('verses_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surahs_id'), 'surahs', ['id'], unique=False)
    op.create_index(op.f('ix_surahs_number'), 'surahs', ['number'], unique=True)
    op.create_table('verses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surah_number', sa.Integer(), nullable=False),
    sa.Column('verse_number', sa.Integer(), nullable=False),
    sa.Column('text_arabic', sa.Text(), nullable=False),
    sa.Column('text_simple', sa.Text(), nullable=True),
    sa.Column('translation_english', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verses_id'), 'verses', ['id'], unique=False)
    op.create_index(op.f('ix_verses_surah_number'), 'verses', ['surah_number'], unique=False)
    op.create_index(op.f('ix_verses_verse_number'), 'verses', ['verse_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verses_verse_number'), table_name='verses')
    op.drop_index(op.f('ix_verses_surah_number'), table_name='verses')
    op.drop_index(op.f('ix_verses_id'), table_name='verses')
    op.drop_table('verses')
    op.drop_index(op.f('ix_surahs_number'), table_name='surahs')
    op.drop_index(op.f('ix_surahs_id'), table_name='surahs')
    op.drop_table('surahs')
    # ### end Alembic commands ###
