"""redesign_isms_table_and_add_lem_root_to_morphology

Revision ID: 9d7c102477a1
Revises: c542342a70aa
Create Date: 2026-03-11 18:01:35.056570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d7c102477a1'
down_revision: Union[str, None] = 'c542342a70aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('isms', 'ism_type',
               existing_type=postgresql.ENUM('PROPER', 'COMMON', name='ismtypeenum'),
               nullable=False)
    op.drop_index('ix_isms_ism', table_name='isms')
    op.drop_column('isms', 'chapter')
    op.drop_column('isms', 'root')
    op.drop_column('isms', 'verse')
    op.drop_column('isms', 'word_num')
    op.drop_column('isms', 'lem')
    op.drop_column('isms', 'token')
    op.add_column('morphology_items', sa.Column('lem', sa.String(length=255), nullable=True))
    op.add_column('morphology_items', sa.Column('root', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('morphology_items', 'root')
    op.drop_column('morphology_items', 'lem')
    op.add_column('isms', sa.Column('token', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('isms', sa.Column('lem', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('isms', sa.Column('word_num', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('isms', sa.Column('verse', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('isms', sa.Column('root', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('isms', sa.Column('chapter', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_isms_ism', 'isms', ['ism'], unique=False)
    op.alter_column('isms', 'ism_type',
               existing_type=postgresql.ENUM('PROPER', 'COMMON', name='ismtypeenum'),
               nullable=True)
    # ### end Alembic commands ###
