"""add_normalized_word_to_morphology

Revision ID: d93f6c8ed991
Revises: 9d7c102477a1
Create Date: 2026-03-11 20:06:42.103476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93f6c8ed991'
down_revision: Union[str, None] = '9d7c102477a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('morphology_items', sa.Column('normalized_word', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('morphology_items', 'normalized_word')
    # ### end Alembic commands ###
