"""add morphology items table

Revision ID: e7a8b694d2dd
Revises: 932e13df7124
Create Date: 2026-03-05 09:15:58.856868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a8b694d2dd'
down_revision: Union[str, None] = '932e13df7124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morphology_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verse', sa.Integer(), nullable=False),
    sa.Column('word_num', sa.Integer(), nullable=False),
    sa.Column('token', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_morphology_items_chapter'), 'morphology_items', ['chapter'], unique=False)
    op.create_index(op.f('ix_morphology_items_id'), 'morphology_items', ['id'], unique=False)
    op.create_index(op.f('ix_morphology_items_token'), 'morphology_items', ['token'], unique=False)
    op.create_index(op.f('ix_morphology_items_verse'), 'morphology_items', ['verse'], unique=False)
    op.create_index(op.f('ix_morphology_items_word_num'), 'morphology_items', ['word_num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_morphology_items_word_num'), table_name='morphology_items')
    op.drop_index(op.f('ix_morphology_items_verse'), table_name='morphology_items')
    op.drop_index(op.f('ix_morphology_items_token'), table_name='morphology_items')
    op.drop_index(op.f('ix_morphology_items_id'), table_name='morphology_items')
    op.drop_index(op.f('ix_morphology_items_chapter'), table_name='morphology_items')
    op.drop_table('morphology_items')
    # ### end Alembic commands ###
